### ISSUE TITLE
Removing geometry description in popuptable

### ISSUE THREAD

**Issue by tim-salabim** [r-spatial/leafpop#2]
Moved here from https://github.com/r-spatial/mapview/issues/224

**Comment by tim-salabim** [comment]
This should now work as expected. If `zcol` is set and the geometry column is not explicitly included, it will not be shown in the popup.

**Comment by ggeniaux** [comment]
Thanks for your quick answer. Il will install the  github version of leafpop and test this new feature.

On my side, I avoid this issue using

x_nosf<- x %>%  st_set_geometry(NULL)
mymap=mapview(x,zcol=‘price',layer.name ='Price',legend=TRUE,popup=popupTable(x_nosf,row.numbers=FALSE,feature.id = FALSE)

**Comment by tim-salabim** [comment]
Yes, that is always an option. But I think that the current approach is cleaner as it handles the sfc column similar to all other columns.

**Comment by ggeniaux** [comment]
I just install the latest leafpop from githup. The geom column still appear in popup.
When I load leadfpop it masks popupGraph, popupImage, popupTable from installed mapView version, so I guess that I use the newest popuptable function.

Another small question: when I use "at" with quantiles in mapView (sf,...), the colors of the legend do not match those of the map. It seems to me that the values of 'at' are not correctly sent to the legend function. Can you tell me how to debug this part of the code (debug(mapView) doesn't work).
Thank you.




Le 21 mai 2019 à 15:05, tim-salabim <notifications@github.com<mailto:notifications@github.com>> a écrit :


Yes, that is always an option. But I think that the current approach is cleaner as it handles the sfc column similar to all other columns.

**Comment by tim-salabim** [comment]
Can you provide a small reproducible example using one of the datasets from mapview (franconia or breweries) to show the behaviour, along with you `sessionInfo()`?

Regarding the quantile color issue, see https://github.com/r-spatial/mapview/issues/219 - still working on this one

**Comment by ggeniaux** [comment]
You will find here a reproducible example with sessionInfo. Thanks.

library(sf)
library(dplyr)
library(mapview)
## example
load('sf_grid.Rdata')
sessionInfo()
pal = mapviewPalette("mapviewRasterColors")
mapview(mygrid['prix_liss'],legend=TRUE,at = quantile(mygrid$prix_liss,prob=seq(0,1,by=0.05)),col.regions = pal(20))

**Comment by tim-salabim** [comment]
This is not reproducible for me as I don't have `sf_grid.Rdata`. Please use one of the datasets provided by mapview. Additionally, you'd need to include the output of your `sessionInfo()` call as otherwise I will see my session info, not yours.

Also, I was referring to the popup issue, not the legend color issue

**Comment by ggeniaux** [comment]
data was attached to my previous email.

If attachment failed again : a link to download it 

https://filesender.renater.fr/?s=download&token=4698581b-0916-4265-c293-c23ceee6c6aa

**Comment by tim-salabim** [comment]
Still, I don't see your sessionInfo and your example is not related to the popup issue

**Comment by ggeniaux** [comment]
Sorry,
It happens with Mac mail when text is after the attached filed. Here the sessionInfo

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mapview_2.7.0 dplyr_0.8.0.1 sf_0.7-3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        pillar_1.3.1      compiler_3.4.4
 [4] later_0.7.3       base64enc_0.1-3   class_7.3-14
 [7] tools_3.4.4       digest_0.6.18     viridisLite_0.3.0
[10] satellite_1.0.1   tibble_2.0.1      lattice_0.20-35
[13] pkgconfig_2.0.2   png_0.1-7         rlang_0.3.1
[16] shiny_1.1.0       DBI_1.0.0         rstudioapi_0.9.0
[19] crosstalk_1.0.0   yaml_2.1.19       e1071_1.7-0
[22] raster_2.8-19     htmlwidgets_1.2   webshot_0.5.0
[25] stats4_3.4.4      classInt_0.3-1    leaflet_2.0.1
[28] grid_3.4.4        tidyselect_0.2.5  glue_1.3.0
[31] R6_2.3.0          sp_1.2-5          purrr_0.2.4
[34] magrittr_1.5      scales_0.5.0.9000 codetools_0.2-15
[37] promises_1.0.1    htmltools_0.3.6   units_0.6-2
[40] assertthat_0.2.0  colorspace_1.3-2  mime_0.5
[43] xtable_1.8-2      httpuv_1.4.4.1    munsell_0.5.0
[46] crayon_1.3.4



Le 22 mai 2019 à 11:10, tim-salabim <notifications@github.com<mailto:notifications@github.com>> a écrit :


Still, I don't see your sessionInfo and your example is not related to the popup issue

**Comment by tim-salabim** [comment]
Ok, so here's what I see with the latest CRAN version of  mapview (2.7.0) and the latest github version of leafpop (0.0.3):

```r
> library(mapview)
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_2.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        raster_2.9-5      magrittr_1.5      units_0.6-2       munsell_0.5.0    
 [6] viridisLite_0.3.0 colorspace_1.4-1  xtable_1.8-3      lattice_0.20-38   R6_2.4.0         
[11] tools_3.6.0       webshot_0.5.1     grid_3.6.0        png_0.1-7         e1071_1.7-0.1    
[16] DBI_1.0.0         class_7.3-15      htmltools_0.3.6   crosstalk_1.0.0   leaflet_2.0.2    
[21] digest_0.6.19     sf_0.7-4          shiny_1.2.0       later_0.8.0       base64enc_0.1-3  
[26] htmlwidgets_1.3   promises_1.0.1    codetools_0.2-16  mime_0.6          sp_1.3-1         
[31] compiler_3.6.0    scales_1.0.0      classInt_0.3-1    stats4_3.6.0      satellite_1.0.1  
[36] httpuv_1.4.5.1   
> mapview(franconia, popup = popupTable(franconia, zcol = 1:3))
Registered S3 method overwritten by 'R.oo':
  method        from       
  throw.default R.methodsS3
Warning message:
'mapview::popupTable' is deprecated.
Use 'leafpop::popupTable' instead.
See help("Deprecated") and help("mapview-deprecated"). 
```
which produces:

![Unbenannt](https://user-images.githubusercontent.com/2826432/58166830-f2a8f180-7c8a-11e9-9e79-926d52463193.PNG)

**Comment by ggeniaux** [comment]
Now it’s ok I’ve the same result as you with zcol=1:9, no more need to drop the geometry in popupTable.

Thanks.

Le 22 mai 2019 à 12:13, tim-salabim <notifications@github.com<mailto:notifications@github.com>> a écrit :


Ok, so here's what I see with the latest CRAN version of mapview (2.7.0) and the latest github version of leafpop (0.0.3):

> library(mapview)
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mapview_2.7.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        raster_2.9-5      magrittr_1.5      units_0.6-2       munsell_0.5.0
 [6] viridisLite_0.3.0 colorspace_1.4-1  xtable_1.8-3      lattice_0.20-38   R6_2.4.0
[11] tools_3.6.0       webshot_0.5.1     grid_3.6.0        png_0.1-7         e1071_1.7-0.1
[16] DBI_1.0.0         class_7.3-15      htmltools_0.3.6   crosstalk_1.0.0   leaflet_2.0.2
[21] digest_0.6.19     sf_0.7-4          shiny_1.2.0       later_0.8.0       base64enc_0.1-3
[26] htmlwidgets_1.3   promises_1.0.1    codetools_0.2-16  mime_0.6          sp_1.3-1
[31] compiler_3.6.0    scales_1.0.0      classInt_0.3-1    stats4_3.6.0      satellite_1.0.1
[36] httpuv_1.4.5.1
> mapview(franconia, popup = popupTable(franconia, zcol = 1:3))
Registered S3 method overwritten by 'R.oo':
  method        from
  throw.default R.methodsS3
Warning message:
'mapview::popupTable' is deprecated.
Use 'leafpop::popupTable' instead.
See help("Deprecated") and help("mapview-deprecated").

which produces:

[Unbenannt]<https://user-images.githubusercontent.com/2826432/58166830-f2a8f180-7c8a-11e9-9e79-926d52463193.PNG>
